# Python data science
## 04: numpy ndarray

Vamos a ver cómo:
* Punto 1: Crear ndarrays en python
* Punto 2: Operar entre columnas
* Punto 3: Seleccionar elementos

# Punto 1:

In [1]:
# importar numpy
import numpy as np

In [2]:
# crear lista con numeros primos
numeros_primos=[2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [3]:
# crear array a partir de lista
array_primos=np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
# crear arrays con ceros o cómo inicializar un arreglo de numpy
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# crear arrays con números
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# array con numeros sucesivos
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# haciendo un reshape para dos dimensiones
array_pares.reshape(2,5)


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Punto 2:

In [9]:
# operaciones aritmeticas sobre np array 1-dimension y 2-dimension
array_impares=array_pares+1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
# multiplicar por 100
array_impares*100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [12]:
# resta entre arrays
array_impares-1
array_impares-array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
# cuidado con la división entre cero
array_impares / array_pares

<ipython-input-13-6e01b3b66170>:2: RuntimeWarning: divide by zero encountered in true_divide
  array_impares / array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [14]:
# métodos asociados a estadística
# suma
array_primos.sum()

129

In [15]:
# promedio
array_primos.mean()

12.9

In [16]:
# varianza
array_primos.var()

73.28999999999999

In [17]:
# como ordenar un np array
array_fibonacci=np.array([55,0,144,1,29,89,5,8,13,1,34,3,2])
array_fibonacci

array([ 55,   0, 144,   1,  29,  89,   5,   8,  13,   1,  34,   3,   2])

In [18]:
# orden ascendente: de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  29,  34,  55,  89, 144])

In [20]:
# orden descendente: de mayor a menor
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  29,  13,   8,   5,   3,   2,   1,   1,   0])

In [21]:
np.sort(array_fibonacci)[::-1]

array([144,  89,  55,  34,  29,  13,   8,   5,   3,   2,   1,   1,   0])

# Punto 3:

In [ ]:
# Como seleccionar elements

In [ ]:
# Seleccionar un elemento

In [23]:
A=np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [24]:
# seleccionar el primer elemento
A[0,0]

0

In [25]:
# seleccionar algún otro elemento
A[1,3]

16

In [ ]:
# Seleccionar varios elementos

In [26]:
# seleccionar por fila
A[1,:]

array([10, 12, 14, 16, 18])

In [28]:
# seleccionar por columna
A[:,4]

array([ 8, 18])

In [ ]:
# Utilizar filter

In [29]:
array_fibonacci

array([ 55,   0, 144,   1,  29,  89,   5,   8,  13,   1,  34,   3,   2])

In [30]:
# conidicion para menores de 20
array_fibonacci<20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [31]:
# filtrar menores de 20
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])

# NuncaParesDeAprender!


