# Python Data Science
## 03: Paquetes

Vamos a ver:
* Punto 1: Qué son los paquetes y su uso
* Punto 2: Diferencias entre funciones y métodos
* Punto 3: Paquetes básicos en ciencia de datos

# Punto 1:

In [1]:
# Cómo importar un paquete
import numpy 

In [3]:
numpy.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# Cómo importar un paquete con acrónimo
import numpy as np

In [5]:
# objeto array de numpy
numpy.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# Cómo cargar una función específica de un paquete

In [6]:
from  numpy import arange

In [7]:
arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Punto 2:

In [ ]:
# Diferencias entre funciones y métodos

In [8]:
A=np.arange(9)

In [9]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
# que tipo de objeto es A
type(A)

numpy.ndarray

In [11]:
# calculando promedio con función de numpy
np.mean(A)

4.0

In [12]:
# calculando promedio con método de objeto
A.mean()

4.0

In [ ]:
# Haciendo un reshape con funciones y métodos

In [13]:
# transformando arreglo con función de numpy
np.reshape(A,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# transformando arreglo con método de objeto
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# NuncaParesDeAprender!!
